version: '0.0.0'

services:
  app:
    build: .
    restart: on-failure
    ports:
      - "8000:8000"
    # environment:
    #   DB_CONNECTION: "postgresql://postgres:postgres@db/postgres"
    # env_file:
    #   - .env
    # depends_on:
    #   - db
